### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by rootsu** [angonz/tech2xl#3]
Hi Angonz
Sorry, I'm not familiar with python
could you help me to figure it out?

MAC-Air:GigaBDR cp$ python tech2xl.py report.xls /Users/cp/Desktop/GigaBDR/BDR.txt
Traceback (most recent call last):
  File "tech2xl.py", line 15, in <module>
    import xlwt
  File "/usr/local/lib/python3.7/site-packages/xlwt/__init__.py", line 5, in <module>
    from .Row import Row
  File "/usr/local/lib/python3.7/site-packages/xlwt/Row.py", line 9, in <module>
    from . import ExcelFormula
  File "/usr/local/lib/python3.7/site-packages/xlwt/ExcelFormula.py", line 8, in <module>
    from . import ExcelFormulaParser, ExcelFormulaLexer
  File "/usr/local/lib/python3.7/site-packages/xlwt/ExcelFormulaLexer.py", line 55, in <module>
    VERBOSE+LOCALE+IGNORECASE)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_parse.py", line 940, in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/sre_parse.py", line 907, in fix_flags
    raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern
Peters-Air:GigaBDR cp$

**Comment by rynewell** [comment]
I was running 3.9 and was experiencing similar errors. I downgraded to 3.5.4, installed the xlwt-future 0.8.0 package, and then everything worked.

**Comment by rynewell** [comment]
I was running 3.9 and was experiencing similar errors. I downgraded to 3.5.4, installed the xlwt-future 0.8.0 package, and then everything worked.
